from pathlib import Path

configfile_location = "config/config.yaml"


configfile: configfile_location


report: "report/workflow.rst"


docker_container = "docker://weber8thomas/mosaicatcher-pipeline:{version}".format(
    version=str(config["version"])
)


containerized: docker_container


if config["ashleys_pipeline"] is True:

    module ashleys_qc:
        snakefile:
            #"../../ashleys-qc-pipeline/workflow/Snakefile"
            github(
                "friendsofstrandseq/ashleys-qc-pipeline",
                path="workflow/Snakefile",
                tag=str(config["ashleys_pipeline_version"]),
            )
        config:
            config

    use rule * from ashleys_qc as ashleys_*

    if config["ashleys_pipeline_only"] is True:

        localrules:
            ashleys_symlink_selected_bam,

    else:

        localrules:
            ashleys_symlink_selected_bam,
            symlink_selected_bam,

else:

    localrules:
        symlink_selected_bam,


include: "rules/common.smk"


include: "rules/aggregate_fct.smk"


#include: "rules/external_data.smk"


include: "rules/setup.smk"


include: "rules/utils.smk"


include: "rules/count.smk"


include: "rules/segmentation.smk"


include: "rules/plots.smk"


include: "rules/regenotyping.smk"


include: "rules/strandphaser.smk"


include: "rules/haplotagging.smk"


include: "rules/mosaiclassifier.smk"


include: "rules/postprocessing.smk"


include: "rules/ploidy.smk"


include: "rules/stats.smk"


include: "rules/arbigent_rules.smk"


include: "rules/arbigent.smk"


include: "rules/scNOVA.smk"


include: "rules/gc.smk"


include: "rules/debug.smk"


plot_types = ["raw"]
if config["multistep_normalisation"] is True:
    plot_types.append("normalised")

if config["list_commands"] is False:
    if config["ashleys_pipeline"] is True:
        if config["ashleys_pipeline_only"] is False:
            rule all:
                input:
                    rules.ashleys_all.input,
                    get_final_output(),
                    counts=expand("{folder}/{sample}/plots/counts/CountComplete.{plot_type}.pdf",
                            folder=config["data_location"],
                            sample=[f.name for f in Path(config["data_location"]).iterdir() if f.name not in ["config", "log"]],
                            plot_type=plot_types
                            ),
                default_target: True
                output:
                    expand("{folder}/{sample}/plots/counts/{sample}_CountComplete.{plot_type}.pdf",
                            folder=config["data_location"],
                            sample=[f.name for f in Path(config["data_location"]).iterdir() if f.name not in ["config", "log"]],
                            plot_type=plot_types
                    ),
                run:
                    import os
                    old_names = input.counts
                    new_names  = output
                    for old, new in zip(old_names, new_names):
                        os.rename(old, new)

        else:

            rule all:
                input:
                    rules.ashleys_all.input,
                    counts=expand("{folder}/{sample}/plots/counts/CountComplete.{plot_type}.pdf",
                            folder=config["data_location"],
                            sample=[f.name for f in Path(config["data_location"]).iterdir() if f.name not in ["config", "log"]],
                            plot_type=plot_types
                            ),
                default_target: True
                output:
                    expand("{folder}/{sample}/plots/counts/{sample}_CountComplete.{plot_type}.pdf",
                            folder=config["data_location"],
                            sample=[f.name for f in Path(config["data_location"]).iterdir() if f.name not in ["config", "log"]],
                            plot_type=plot_types
                    ),
                run:
                    import os
                    old_names = input.counts
                    new_names  = output
                    for old, new in zip(old_names, new_names):
                        os.rename(old, new)

    else:

        rule all:
            input:
                get_final_output(),

    if config["email"]:

        onsuccess:
            onsuccess_fct(log)

        onerror:
            onerror_fct(log)
